# Generated by Django 2.1.7 on 2019-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_plate_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='counter',
            field=models.IntegerField(null=True),
        ),
    ]
